### ISSUE TITLE
Music Sidebar

### ISSUE THREAD

**Issue by perryliao** [CPSC-436I-Project/Musico#27]
### Screenshots
![image](https://user-images.githubusercontent.com/26581943/83955182-ff9c7280-a804-11ea-998c-471183fda515.png)

**Comment by aditya10** [comment]
design, implement, integrate vote buttons and update votes with redux + mongo support. Songs should be ordered by # of upvotes

**Comment by BreanneHuang** [comment]
This is a duplicate issue, check [#78](https://github.com/CPSC-436I-Project/Musico/issues/78); closing.

**Comment by BreanneHuang** [comment]
This is a duplicate issue, check [#78](https://github.com/CPSC-436I-Project/Musico/issues/78); closing.
