### ISSUE TITLE
Dashboard components

### ISSUE THREAD

**Issue by perryliao** [CPSC-436I-Project/Musico#32]
### Description
- probably more to come when we add more things on the dashboard

### Screenshots
![image](https://user-images.githubusercontent.com/26581943/83955249-9d903d00-a805-11ea-913c-d919ef29a376.png)

**Comment by perryliao** [comment]
Maybe @aditya10 can pitch in with more design ideas?

**Comment by aditya10** [comment]
@jyan317 you want to close this?
