### ISSUE TITLE
Implement Redux

### ISSUE THREAD

**Issue by perryliao** [CPSC-436I-Project/Musico#37]
- [x] chat room genre selected toggle @perryliao 
- [x] profile picture src @aditya10 
- [x] AddSongForm store songs list @aditya10 
- [ ] sidebars' states (collapsed or not) @BreanneHuang 
- [x] Signup form (email, username, password...) **Don't worry about encryption yet** @jyan317 
- [ ] Songs Queue
- [ ] Dashboard items

**Comment by aditya10** [comment]
Closing this because #27 #78
