### ISSUE TITLE
Expandable buttons

### ISSUE THREAD

**Issue by perryliao** [CPSC-436I-Project/Musico#5]
### Description
The 2 buttons you see at the main menu, should be able to expand when you click on it
- create the expanding function within the component class, then pass it in as the component's callback prop
- extends #4 

### Required Props
- `text: String` The text that gets displayed on it
- `colour: String` Colour of the button, 

### Screenshots
![image](https://user-images.githubusercontent.com/26581943/83475986-69eb9680-a444-11ea-80a3-a63724a15b43.png)
![image](https://user-images.githubusercontent.com/26581943/83476267-17f74080-a445-11ea-87b1-954deae4b834.png)

**Comment by aditya10** [comment]
Done!
